name: utils
channels:
    - default
    - conda-forge
dependencies:
    - python==3.9.*
    - ipython
    - jupyter
    - black
    - tqdm
    - numpy
    - scipy
    - pandas
    - matplotlib
    - seaborn